### ISSUE TITLE
Can okvis work on low-level IMU?

### ISSUE THREAD

**Issue by francescoli** [ethz-asl/okvis#3]
Hi,
  Is okvis sensitive to IMU‘s accuracy and IMU-Cam synchronization? I test it using the data from my mobile phone with modified configure file. Result seems bad. Have I missed any important steps , or maybe okvis cannot work on low-level IMU?

**Comment by sleutenegger** [comment]
This is described in the README. Accurate calibration and synchronisation is *very* important.
