### ISSUE TITLE
How to compare With EuRoc groundtruth?

### ISSUE THREAD

**Issue by David-Willo** [ethz-asl/okvis#36]
Now I am running Okvis using EuRoc MAV Dataset and trying to compare the pose with the ground truth given in the dataset. I add some code in the publishFullStateAsCallback to  save position data and velocity data which are the same with the data displayed on the poseViewer. However, when i compare the result with the ground truth, I found the pose is different. How can I make a comparison ?

**Comment by weblucas** [comment]
depending of the euroc sequence, the ground truth is provided in a different coordinate system, usually in the top of the UAV. OKVIS by default will provide the pose centered in the camera. you can change the config file to use a custom world frame. There you can add the tranformation between the imu(B-body) and the origin of the Euroc UAV (S) [look this image- you need T_SB](http://projects.asl.ethz.ch/datasets/lib/exe/fetch.php?w=400&media=platform.jpg)

**Comment by David-Willo** [comment]
Thanks! Let me have a try.

**Comment by aforster** [comment]
@weblucas default pose is IMU pose not camera if I remember correctly

**Comment by David-Willo** [comment]
![Uploading Screenshot from 2017-05-18 10-43-05.png…]()
![Uploading image.png…]()
I change the world frame like this, but the output doesn't seem to change. Anything wrong?

**Comment by David-Willo** [comment]
![image](https://cloud.githubusercontent.com/assets/14790278/26184767/51ca886e-3bb9-11e7-82c1-dafb95d5ad69.png)
The origin world frame looks like this.

**Comment by Chandrahas1991** [comment]
@weblucas  Could you please confirm if the pose is IMU or camera centered ? README says IMU

**Comment by Chandrahas1991** [comment]
@David-Willo How did you compute the extrinsics between okvis (IMU) output and ground truth ?

**Comment by David-Willo** [comment]
@Chandrahas1991 Well, I made a mistake at that time.
To compare the OKVIS pose output with the EuRoc ground truth, we need to associate the data sequences (according to the timestamp), since the sequence length is usually different. Then we can compute the translation and rotation between the two coordinate system. Have a look at the TUM toolkit, it helps a lot.

**Comment by Chandrahas1991** [comment]
@David-Willo Thanks for your response. Could you please share the link of that toolkit ?

**Comment by Chandrahas1991** [comment]
@David-Willo Also, is it incorrect if for every datapoint's timestamp in the okvis estimate, i look for the closest timestamp in the groundtruth data ? (and then perform the transformation between the two coordinate systems)

**Comment by David-Willo** [comment]
@Chandrahas1991 https://vision.in.tum.de/data/datasets/rgbd-dataset/tools there are some description and a download link in it.

**Comment by Chandrahas1991** [comment]
@David-Willo Thanks!

**Comment by jzubizarreta** [comment]
Same problem here! Did you manage to solve the problem?
If yes, could you share with me your tool to synchronize images with the ground truth pose of the cameras?

Thanks in advance,

Jon

**Comment by Chandrahas1991** [comment]
@jzubizarreta Have a look at the link @David-Willo has shared. Specifically the "Absolute Trajectory Error" script. As long as your timestamps from both the systems are in same precision, the script will align the pose and ground-truth using a stable method. Additionally you can also save the aligned poses using the "-save_associations" flag.

**Comment by jzubizarreta** [comment]
@Chandrahas1991 Thanks!

**Comment by cumtchenchang** [comment]
@David-Willo same question. I change the cold, but I can not get the generate pose to compare the ground truth. May you share your cold, I just want you get OKVIS trajectory to evelate. Please.
