### ISSUE TITLE
error: ‘function’ is not a member of ‘std’

### ISSUE THREAD

**Issue by giwrgosg** [ethz-asl/okvis#81]
I have Ubuntu 18 and I keep receiving the following error:

> /okvis_g/build/brisk/src/brisk_external/src/brisk-feature-detector.cc:61:8: error: ‘function’ is not a member of ‘std’
>    std::function<bool(const cv::KeyPoint& key_pt)> masking =

Any suggestions?

**Update**: I added in the file "brisk-feature-detector.cc" the 

> #include \<functional\>

 and it worked.

**Comment by Astronirav** [comment]
I had a similar problem on Ubuntu 18 and I solved it by changing compiler.
